" file:     ~/.gvimrc files
" author:   Simon Gomizelj
" ----------------------------------------------------------------------------

"colorscheme molokai

set guifont=Source\ Code\ Pro\ for\ Powerline\ 11
set guioptions=agpi
set guicursor=a:blinkon0
set mousef

syntax enable
set background=dark
colorscheme solarized

set lines=40
set columns=90

set mouses=i-r:beam,s:updown,sd:udsizing,vs:leftright,vd:lrsizing,m:no,ml:up-arrow,v:rightup-arrow
set mousehide
